name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Clean up old build files (if any)
        run: |
          rm -rf nanemu-*

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build the Go binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o nanemu-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/nanemu

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: nanemu-bin-${{ github.run_id }}  # Уникальное имя артефакта для каждого run
          path: nanemu-*

      - name: Upload release binary (optional)
        uses: softprops/action-gh-release@v1
        with:
          files: nanemu-*
